name: Update submodules
on:
  workflow_dispatch:
  # "At 00:00 on Monday."(UTC) - https://crontab.guru/#0_0_*_*_1
  schedule:
    - cron:  '0 0 * * 1'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Update submodules
        run: |
          SUBMODULES=(frontend backend openapi)
          for module in ${SUBMODULES[@]}; do
            echo "Try to update submodule: $module"
            git submodule update --remote "$module"
            if git diff --exit-code --quiet; then
              echo "No updates available."
            else
              echo "Updates are available!"
            fi
            echo "Done: $module"
          done
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore: update submodules"
          committer: "github-actions[bot] github-actions[bot]@users.noreply.github.com"
          title: "Auto update submodules"
          body: "This PR is created to update submodules by GitHub Actions."
          branch-suffix: "short-commit-hash"
          delete-branch: "true"
